### ISSUE TITLE
[Bug] It doesn't recognize `mailto:` scheme

### ISSUE THREAD

**Issue by Divlo** [styfle/links-awakening#6]
Hello! :wave:
Thanks for this awesome utility, that might be run in CI to avoid broken links. :+1:

I tried it on my website, and it seems like all my links are working. :smile:
However, I've got this: `mailto:contact@divlo.fr (status: unknown scheme, referer: https://divlo.fr/)`.
It doesn't yet recognize `mailto:` scheme, I don't know if it's easy to know if a email is valid or not, but if it is complicated, and not in the scope of this utility, I'd rather having a warning to tell me that it couldn't be validated instead of an error.

**Comment by styfle** [comment]
Thanks for reporting, this is definitely a bug!

I think we need to special case `mailto:` and perhaps any protocol.

Right now there is a regex to check for `http:`  and `https:` so we could check for `mailto:` and ignore it.

Another option is to try/catch `new URL()` to first parse and then check the protocol to ignore away anything that is not http/s. For example, I'm not sure if we want to check `file:` protocol links.
